<br/>
<img src="images/skillnest_logo.svg" alt="SkillNest" width="280px" align="left"/>
<img src="images/skillnest_logo.svg" alt="SkillNest" width="280px" align="right"/>
<div align="center">
<h2>Bootcamp Data Science — Módulo 1</h2><br/>
<h1>Semana 2 — Pandas</h1>
<h3>Introducción, Filtrado y Limpieza de datos</h3>
<br/>
</div>

---
<div style="background:linear-gradient(90deg,#6C3CE1,#00C9A7);padding:2px;border-radius:10px">
<div style="background:#0F0F1A;border-radius:9px;padding:20px 30px">
<h1 style="color:white;margin:0">📚 Clase 1</h1>
<h2 style="color:#00C9A7;margin:0">Introducción a Pandas</h2>
</div>
</div>

# ¿Qué es Pandas?

**Pandas** es la librería de Python más usada para trabajar con datos en tabla — piénsala como un **Excel con superpoderes**.

| Excel | Pandas |
|-------|--------|
| Hoja de cálculo | DataFrame |
| Columna | Series |
| Fórmulas | Métodos Python |
| ~1M filas máximo | Millones de filas |
| Sin automatización | 100% automatizable |

> 📦 Pandas se construye sobre **NumPy** y es el corazón de todo flujo de trabajo de Data Science con Python.

# Importar Pandas

Antes de usar pandas hay que **importarlo**. La convención universal es `import pandas as pd`.  
Esta línea va **una sola vez** al inicio del notebook.

In [1]:
import pandas as pd

print(f"Versión de pandas: {pd.__version__}")

Versión de pandas: 2.2.3

# Estructuras de datos: Series

Una **Series** es una columna — una lista de valores con un índice.

```python
pd.Series(data, index=...)
```

In [2]:
import pandas as pd

# Serie con índice automático (0, 1, 2...)
hp_pokemon = pd.Series([45, 60, 80, 45, 39], name="HP")
print(hp_pokemon)
print(f"\nTipo: {type(hp_pokemon)}")
print(f"Largo: {len(hp_pokemon)}")

# Serie con índice personalizado
hp_pokemon_named = pd.Series(
    [45, 60, 80, 45, 39],
    index=["Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon"],
    name="HP"
)
print("\n", hp_pokemon_named)

0    45
1    60
2    80
3    45
4    39
Name: HP, dtype: int64

Tipo: <class 'pandas.core.series.Series'>
Largo: 5

 Bulbasaur     45
Ivysaur       60
Venusaur      80
Charmander    45
Charmeleon    39
Name: HP, dtype: int64

# Estructuras de datos: DataFrame

Un **DataFrame** es una tabla completa — filas y columnas.  
Cada columna es una Series. Podemos crearlo desde un **diccionario**:

In [3]:
import pandas as pd

# Crea un DataFrame desde un diccionario — cada llave es una columna
pokedex = pd.DataFrame({
    "Nombre":     ["Bulbasaur", "Charmander", "Squirtle", "Pikachu"],
    "Tipo":       ["Planta",    "Fuego",      "Agua",     "Eléctrico"],
    "HP":         [45,          39,           44,         35],
    "Ataque":     [49,          52,           48,         55],
    "Legendario": [False,       False,        False,      False]
})

pokedex

       Nombre       Tipo  HP  Ataque  Legendario
0   Bulbasaur     Planta  45      49       False
1  Charmander      Fuego  39      52       False
2    Squirtle       Agua  44      48       False
3     Pikachu  Eléctrico  35      55       False

# Leer archivos: `pd.read_csv()`

En la práctica casi nunca creamos DataFrames a mano — los **leemos desde archivos**.

```python
df = pd.read_csv("ruta/al/archivo.csv")      # CSV
df = pd.read_excel("ruta/al/archivo.xlsx")   # Excel
df = pd.read_json("ruta/al/archivo.json")    # JSON
```

> 💡 En **Google Colab** primero hay que subir el archivo:  
> Panel izquierdo → 📁 → Subir → luego usar la ruta `"/content/nombre.csv"`

In [4]:
import pandas as pd

# Cargamos el dataset de Pokémon — 800 pokémon con sus estadísticas
df = pd.read_csv("data/pokemon.csv")
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

# Exploración inicial — los 5 métodos esenciales

Cada vez que cargues un dataset nuevo, ejecuta estos en orden:

In [5]:
# 1. ¿Cuántas filas y columnas tiene?
print(f"Shape: {df.shape}")
print(f"→ {df.shape[0]} pokémon, {df.shape[1]} columnas\n")

# 2. Primeras filas (vista rápida)
df.head()

Shape: (800, 13)
→ 800 pokémon, 13 columnas

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [ ]:
# 3. Tipos de datos y valores no nulos por columna
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

In [7]:
# 4. Estadísticas descriptivas de columnas numéricas
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [8]:
# 5. Últimas 3 filas
df.tail(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

# Seleccionar columnas

| Sintaxis | Retorna | Cuándo usarlo |
|----------|---------|----------------|
| `df['col']` | Series | Seleccionar 1 columna |
| `df[['col1','col2']]` | DataFrame | Seleccionar varias columnas |
| `df.loc[filas, cols]` | Flexible | Por etiqueta (nombre) |
| `df.iloc[filas, cols]` | Flexible | Por posición numérica |

In [9]:
import pandas as pd
df = pd.read_csv("data/pokemon.csv")

# Una columna → Series
print(df['Name'].head())
print()

# Varias columnas → DataFrame
df[['Name', 'Type 1', 'HP', 'Attack']].head(8)

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

                        Name Type 1  HP  Attack
0                  Bulbasaur  Grass  45      49
1                    Ivysaur  Grass  60      62
2                   Venusaur  Grass  80      82
3      VenusaurMega Venusaur  Grass  80     100
4                 Charmander   Fire  39      52
5                 Charmeleon   Fire  58      64
6                  Charizard   Fire  78      84
7  CharizardMega Charizard X   Fire  78     130

In [10]:
# loc: por nombre de fila y columna
# df.loc[filas, columnas]
df.loc[0:4, ['Name', 'Type 1', 'Total']]

                    Name Type 1  Total
0              Bulbasaur  Grass    318
1                Ivysaur  Grass    405
2               Venusaur  Grass    525
3  VenusaurMega Venusaur  Grass    625
4             Charmander   Fire    309

In [11]:
# iloc: por posición numérica
# df.iloc[filas, columnas]
df.iloc[0:5, 0:4]   # primeras 5 filas, primeras 4 columnas

   #                   Name Type 1  Type 2
0  1              Bulbasaur  Grass  Poison
1  2                Ivysaur  Grass  Poison
2  3               Venusaur  Grass  Poison
3  3  VenusaurMega Venusaur  Grass  Poison
4  4             Charmander   Fire     NaN

### 🔹 Mini-ejercicio 1

1. Carga `data/pokemon.csv` en un DataFrame llamado `df`
2. Imprime el shape y el número de pokémon legendarios (`Legendary == True`)
3. Muestra solo las columnas `Name`, `Type 1`, `HP`, `Attack`, `Defense`, `Speed` de los primeros 10 pokémon

In [12]:
# Mini-ejercicio 1
df = pd.read_csv("data/pokemon.csv")

df.shape

(800, 13)

In [42]:
print(df['Legendary'].sum())

65

In [20]:
contando = df['Legendary'].value_counts()
print(contando)

Legendary
False    735
True      65
Name: count, dtype: int64

In [44]:
legendarios = df[df['Legendary'] == True]
legendarios.sample(15)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
703,641,TornadusTherian Forme,Flying,NaN,580,79,100,80,110,90,121,5,True
538,481,Mesprit,Psychic,NaN,580,80,105,105,105,105,80,4,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
551,492,ShayminSky Forme,Grass,Flying,600,100,103,75,120,75,127,4,True
263,244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True
707,644,Zekrom,Dragon,Electric,680,100,150,120,120,100,90,5,True
710,646,Kyurem,Dragon,Ice,660,125,130,90,130,90,95,5,True
712,646,KyuremWhite Kyurem,Dragon,Ice,700,125,120,90,170,100,95,5,True
542,485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
711,646,KyuremBlack Kyurem,Dragon,Ice,700,125,170,100,120,90,95,5,True
553,494,Victini,Psychic,Fire,600,100,100,100,100,100,100,5,True
704,642,ThundurusIncarnate Forme,Electric,Flying,580,79,115,70,125,80,111,5,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True

In [48]:
primeros_diez = df[['Name', 'Type 1', 'HP', 'Attack', 'Defense', 'Speed']].head(10)
primeros_diez

                        Name Type 1  HP  Attack  Defense  Speed
0                  Bulbasaur  Grass  45      49       49     45
1                    Ivysaur  Grass  60      62       63     60
2                   Venusaur  Grass  80      82       83     80
3      VenusaurMega Venusaur  Grass  80     100      123     80
4                 Charmander   Fire  39      52       43     65
5                 Charmeleon   Fire  58      64       58     80
6                  Charizard   Fire  78      84       78    100
7  CharizardMega Charizard X   Fire  78     130      111    100
8  CharizardMega Charizard Y   Fire  78     104       78    100
9                   Squirtle  Water  44      48       65     43

In [47]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [52]:
#regla 1: 
poderosos = df[(df['Attack'] > 100) & (df['Defense'] > 90) & (df['Sp. Atk'] > 95) & (df['Sp. Def'] > 90) & (df['Speed'] > 90)]
poderosos

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False
420,381,LatiosMega Latios,Dragon,Psychic,700,80,130,100,160,120,110,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False
541,484,Palkia,Water,Dragon,680,90,120,100,150,120,100,4,True
552,493,Arceus,Normal,NaN,720,120,120,120,120,120,120,4,True
717,649,Genesect,Bug,Steel,600,71,120,95,120,95,99,5,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True

---
<div style="background:linear-gradient(90deg,#6C3CE1,#00C9A7);padding:2px;border-radius:10px">
<div style="background:#0F0F1A;border-radius:9px;padding:20px 30px">
<h1 style="color:white;margin:0">📚 Clase 2</h1>
<h2 style="color:#00C9A7;margin:0">Filtrado de DataFrames</h2>
</div>
</div>

# ¿Cómo funciona el filtrado?

El filtrado en pandas usa **condiciones booleanas** — igual a como aprendimos en Python, pero aplicado a columnas completas.

```python
# Paso 1: crear la condición (produce True/False por fila)
condicion = df['columna'] > valor

# Paso 2: aplicar el filtro al DataFrame
df_filtrado = df[condicion]

# O en una línea:
df_filtrado = df[df['columna'] > valor]
```

In [22]:
import pandas as pd
df = pd.read_csv("data/pokemon.csv")

# ¿Cuántos pokémon tienen HP mayor a 100?
condicion_hp = df['HP'] > 100

print(f"Tipo de la condición: {type(condicion_hp)}")
print(f"Primeros valores:")
print(condicion_hp.head(8))
print(f"\nTotal con HP > 100: {condicion_hp.sum()}")

Tipo de la condición: <class 'pandas.core.series.Series'>
Primeros valores:
0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: HP, dtype: bool

Total con HP > 100: 67

# Filtros simples

In [23]:
import pandas as pd
df = pd.read_csv("data/pokemon.csv")

# Pokémon de tipo Fuego
df_fuego = df[df['Type 1'] == 'Fire']
print(f"Pokémon de tipo Fuego: {len(df_fuego)}")
df_fuego[['Name', 'Type 1', 'Attack', 'Speed']].head(8)

Pokémon de tipo Fuego: 52

                         Name Type 1  Attack  Speed
4                  Charmander   Fire      52     65
5                  Charmeleon   Fire      64     80
6                   Charizard   Fire      84    100
7   CharizardMega Charizard X   Fire     130    100
8   CharizardMega Charizard Y   Fire     104    100
42                     Vulpix   Fire      41     65
43                  Ninetales   Fire      76    100
63                  Growlithe   Fire      70     60

In [24]:
# Pokémon con ataque mayor o igual a 130
df_fuertes = df[df['Attack'] >= 130]
print(f"Pokémon muy fuertes (Attack ≥ 130): {len(df_fuertes)}")
df_fuertes[['Name', 'Type 1', 'Attack']].sort_values('Attack', ascending=False)

Pokémon muy fuertes (Attack ≥ 130): 66

                        Name   Type 1  Attack
163      MewtwoMega Mewtwo X  Psychic     190
232  HeracrossMega Heracross      Bug     185
429       DeoxysAttack Forme  Psychic     180
424    GroudonPrimal Groudon   Ground     180
426    RayquazaMega Rayquaza   Dragon     180
..                       ...      ...     ...
270                    Ho-oh     Fire     130
147                  Flareon     Fire     130
493                 Garchomp   Dragon     130
524                Mamoswine      Ice     130
710                   Kyurem   Dragon     130

[66 rows x 3 columns]

# Filtros múltiples: `&` (and), `|` (or), `~` (not)

> ⚠️ Importante: en pandas usamos `&`, `|`, `~` en lugar de `and`, `or`, `not`  
> Y cada condición debe ir entre **paréntesis**

In [25]:
import pandas as pd
df = pd.read_csv("data/pokemon.csv")

# Pokémon de tipo Fuego Y que sean de la 1ra generación
df_fuego_gen1 = df[(df['Type 1'] == 'Fire') & (df['Generation'] == 1)]
print(f"Fuego + Gen 1: {len(df_fuego_gen1)}")
df_fuego_gen1[['Name', 'Type 1', 'Generation', 'Attack']].head()

Fuego + Gen 1: 14

                        Name Type 1  Generation  Attack
4                 Charmander   Fire           1      52
5                 Charmeleon   Fire           1      64
6                  Charizard   Fire           1      84
7  CharizardMega Charizard X   Fire           1     130
8  CharizardMega Charizard Y   Fire           1     104

In [26]:
# Pokémon de tipo Agua O Fuego
df_agua_fuego = df[(df['Type 1'] == 'Water') | (df['Type 1'] == 'Fire')]
print(f"Agua o Fuego: {len(df_agua_fuego)}")

# Pokémon que NO son legendarios y tienen HP > 90
df_nolegen_hp = df[~df['Legendary'] & (df['HP'] > 90)]
print(f"No legendarios con HP > 90: {len(df_nolegen_hp)}")
df_nolegen_hp[['Name', 'Type 1', 'HP', 'Legendary']].head(6)

Agua o Fuego: 164
No legendarios con HP > 90: 97

                   Name  Type 1   HP  Legendary
41             Clefable   Fairy   95      False
44           Jigglypuff  Normal  115      False
45           Wigglytuff  Normal  140      False
86              Slowbro   Water   95      False
87  SlowbroMega Slowbro   Water   95      False
96                  Muk  Poison  105      False

# Filtrar con `.isin()` — lista de valores

In [27]:
import pandas as pd
df = pd.read_csv("data/pokemon.csv")

# Pokémon de los tipos "Starter" clásicos
tipos_starter = ['Fire', 'Water', 'Grass']
df_starters = df[df['Type 1'].isin(tipos_starter)]

print(f"Pokémon de tipo Fuego, Agua o Planta: {len(df_starters)}")

# value_counts() — distribución de valores en una columna
df_starters['Type 1'].value_counts()

Pokémon de tipo Fuego, Agua o Planta: 234

Type 1
Water    112
Grass     70
Fire      52
Name: count, dtype: int64

# Filtrar texto con `.str.contains()`

In [28]:
import pandas as pd
df = pd.read_csv("data/pokemon.csv")

# Pokémon cuyo nombre contiene "Mega"
df_mega = df[df['Name'].str.contains('Mega')]
print(f"Pokémon Mega: {len(df_mega)}")
df_mega[['Name', 'Type 1', 'Total']].head(8)

Pokémon Mega: 49

                         Name   Type 1  Total
3       VenusaurMega Venusaur    Grass    625
7   CharizardMega Charizard X     Fire    634
8   CharizardMega Charizard Y     Fire    634
12    BlastoiseMega Blastoise    Water    630
19      BeedrillMega Beedrill      Bug    495
23        PidgeotMega Pidgeot   Normal    579
71      AlakazamMega Alakazam  Psychic    590
87        SlowbroMega Slowbro    Water    590

In [29]:
# Pokémon cuyo nombre empieza por "Char"
df_char = df[df['Name'].str.startswith('Char')]
print(f"Pokémon 'Char': {len(df_char)}")
df_char[['Name', 'Type 1', 'Attack', 'Speed']]

Pokémon 'Char': 5

                        Name Type 1  Attack  Speed
4                 Charmander   Fire      52     65
5                 Charmeleon   Fire      64     80
6                  Charizard   Fire      84    100
7  CharizardMega Charizard X   Fire     130    100
8  CharizardMega Charizard Y   Fire     104    100

# `value_counts()` — explorar distribuciones

In [30]:
import pandas as pd
df = pd.read_csv("data/pokemon.csv")

# ¿Cuántos pokémon hay de cada tipo principal?
print("Distribución por Type 1:")
print(df['Type 1'].value_counts())
print()

# Con normalización (porcentaje)
print("\n% por generación:")
print(df['Generation'].value_counts(normalize=True).round(3) * 100)

Distribución por Type 1:
Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Rock         44
Electric     44
Ground       32
Ghost        32
Dragon       32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64


% por generación:
Generation
1    20.8
5    20.6
3    20.0
4    15.1
2    13.2
6    10.2
Name: proportion, dtype: float64

### 🔹 Mini-ejercicio 2

Usando el dataset de Pokémon, responde:
1. ¿Cuántos pokémon son legendarios?
2. ¿Cuántos pokémon tienen un `Total` mayor a 500?
3. ¿Cuántos pokémon de tipo Psíquico (`Psychic`) hay en la Generación 1?
4. ¿Cuál es el pokémon más rápido (`Speed`) que NO sea legendario?
5. Lista los 5 tipos con más representantes (`Type 1`)

In [2]:
# Mini-ejercicio 2
import pandas as pd
df = pd.read_csv("data/pokemon.csv")

In [16]:
df['Legendary'].value_counts()

Legendary
False    735
True      65
Name: count, dtype: int64

In [20]:
print(df['Legendary'].sum())

65

In [6]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [ ]:
len(df[df['Total'] > 500])

224

In [34]:
df_psych_gen1 = df[(df['Type 1'] == 'Psychic') & (df['Generation'] == 1)]
print(f"Psíquico + Gen 1: {len(df_psych_gen1)}")

Psíquico + Gen 1: 11

In [5]:
siquico = df['Type 1'] == 'Psychic'
gen1 = df['Generation'] == 1

filtroseparado = df[siquico & gen1]
print(f"Psíquico + Gen 1: {len(filtroseparado)}")

Psíquico + Gen 1: 11

In [15]:
#rapidos = df.sort_values('Speed', ascending=False)
noLegendario =df['Legendary'] == False
mas_rapido =df.loc[noLegendario].sort_values('Speed', ascending=False).iloc[0]
print(f"Pokémon: {mas_rapido['Name']}. Velocidad: {mas_rapido['Speed']}")

Pokémon: Ninjask. Velocidad: 160

In [14]:
df['Type 1'].value_counts().sort_values(ascending=False).head(5)

Type 1
Water      112
Normal      98
Grass       70
Bug         69
Psychic     57
Name: count, dtype: int64

---
<div style="background:linear-gradient(90deg,#6C3CE1,#00C9A7);padding:2px;border-radius:10px">
<div style="background:#0F0F1A;border-radius:9px;padding:20px 30px">
<h1 style="color:white;margin:0">📚 Clase 3</h1>
<h2 style="color:#00C9A7;margin:0">Limpieza de Datos</h2>
</div>
</div>

# ¿Por qué limpiar datos?

> *"Los científicos de datos pasan el **80% del tiempo** limpiando datos y el 20% quejándose de limpiar datos."*

Los datos reales tienen problemas:
- 🕳️ **Valores nulos** — campos vacíos o sin respuesta
- 👯 **Duplicados** — filas repetidas
- 🔤 **Tipos incorrectos** — fechas como texto, números como strings
- 🗑️ **Columnas irrelevantes** — datos que no sirven para el análisis
- ✏️ **Nombres inconsistentes** — `"Male"`, `"male"`, `"M"`, `"Hombre"`

Vamos a usar el dataset **Titanic** — tiene todos estos problemas 🚢

In [ ]:
import pandas as pd

df = pd.read_csv("data/titanic.csv")
print(f"Shape: {df.shape}")
df.head()

# Detectar valores nulos

In [ ]:
import pandas as pd
df = pd.read_csv("data/titanic.csv")

# ¿Cuántos nulos hay en cada columna?
nulos = df.isnull().sum()
print("Nulos por columna:")
print(nulos)

print()

# Porcentaje de nulos — más útil
pct_nulos = (df.isnull().sum() / len(df) * 100).round(1)
print("\n% de nulos por columna:")
print(pct_nulos[pct_nulos > 0])

In [ ]:
# Ver las filas que tienen nulos en 'Age'
df[df['Age'].isnull()][['Name', 'Sex', 'Age', 'Pclass']].head(8)

# Manejar valores nulos: `dropna()` y `fillna()`

| Método | Cuándo usarlo |
|--------|---------------|
| `dropna()` | Cuando hay pocos nulos y perder filas no importa |
| `fillna(valor)` | Rellenar con un valor fijo (0, "Desconocido") |
| `fillna(df['col'].mean())` | Rellenar con el promedio (variables numéricas) |
| `fillna(df['col'].mode()[0])` | Rellenar con la moda (variables categóricas) |

In [ ]:
import pandas as pd
df = pd.read_csv("data/titanic.csv")

print(f"Filas originales: {len(df)}")

# Eliminar filas donde Age es nulo
df_sin_nulos_age = df.dropna(subset=['Age'])
print(f"Después de dropna en Age: {len(df_sin_nulos_age)}")

# Mejor opción: rellenar Age con la mediana (más robusta que la media)
mediana_age = df['Age'].median()
df['Age'] = df['Age'].fillna(mediana_age)
print(f"\nMediana de edad usada: {mediana_age}")
print(f"Nulos en Age después de fillna: {df['Age'].isnull().sum()}")

In [ ]:
import pandas as pd
df = pd.read_csv("data/titanic.csv")

# Cabin tiene 77% de nulos — rellenar con "Desconocido"
df['Cabin'] = df['Cabin'].fillna('Desconocido')

# Embarked tiene solo 2 nulos — rellenar con la moda
moda_embarked = df['Embarked'].mode()[0]
df['Embarked'] = df['Embarked'].fillna(moda_embarked)

# Verificar
print("Nulos restantes:")
print(df.isnull().sum()[df.isnull().sum() > 0])
print("\n✅ Dataset limpio de nulos")

# Eliminar duplicados

In [ ]:
import pandas as pd
df = pd.read_csv("data/titanic.csv")

# ¿Hay filas duplicadas?
n_duplicados = df.duplicated().sum()
print(f"Filas duplicadas: {n_duplicados}")

# Eliminar duplicados (mantiene la primera ocurrencia)
df = df.drop_duplicates()
print(f"Shape después de drop_duplicates: {df.shape}")

# También podemos buscar duplicados por columnas específicas
# df.duplicated(subset=['Name', 'Age']).sum()

# Renombrar y eliminar columnas

In [ ]:
import pandas as pd
df = pd.read_csv("data/titanic.csv")

# Renombrar columnas — más descriptivas y en español
df = df.rename(columns={
    'PassengerId': 'id',
    'Survived':    'sobrevivio',
    'Pclass':      'clase',
    'Name':        'nombre',
    'Sex':         'sexo',
    'Age':         'edad',
    'SibSp':       'hermanos_conyuges',
    'Parch':       'padres_hijos',
    'Ticket':      'ticket',
    'Fare':        'tarifa',
    'Cabin':       'cabina',
    'Embarked':    'puerto_embarque'
})

print("Columnas renombradas:")
print(df.columns.tolist())
df.head(3)

In [ ]:
# Eliminar columnas que no nos sirven para el análisis
df = df.drop(columns=['ticket', 'cabina', 'id'])

print(f"Columnas después de eliminar: {df.columns.tolist()}")
df.head()

# Cambiar tipos de datos

In [ ]:
import pandas as pd
df = pd.read_csv("data/titanic.csv")

print("Tipos originales:")
print(df.dtypes)

# 'Survived' y 'Pclass' son int pero representan categorías
# .astype() para convertir
df['Survived'] = df['Survived'].astype(bool)
df['Pclass']   = df['Pclass'].astype(str)  # tratar como categoría

print("\nTipos después de conversión:")
print(df[['Survived', 'Pclass']].dtypes)

# Verificar valores únicos
print(f"\nValores en Pclass: {df['Pclass'].unique()}")
print(f"Survived es bool: {df['Survived'].dtype}")

# Ordenar datos: `sort_values()`

In [ ]:
import pandas as pd
df = pd.read_csv("data/titanic.csv")

# Ordenar por tarifa de mayor a menor
df_ordenado = df.sort_values('Fare', ascending=False)
df_ordenado[['Name', 'Pclass', 'Fare', 'Survived']].head(8)

In [ ]:
# Ordenar por múltiples columnas
df_multi = df.sort_values(['Pclass', 'Age'], ascending=[True, False])
df_multi[['Name', 'Pclass', 'Age', 'Survived']].head(8)

# Pipeline de limpieza completo

Aplicar todos los pasos juntos — así se hace en un proyecto real:

In [ ]:
import pandas as pd

# 1. Cargar
df = pd.read_csv("data/titanic.csv")
print(f"[1] Original:       {df.shape}")

# 2. Eliminar columnas irrelevantes
df = df.drop(columns=['PassengerId', 'Ticket', 'Cabin', 'Name'])
print(f"[2] Sin columnas:   {df.shape}")

# 3. Tratar nulos
df['Age']      = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
print(f"[3] Nulos tratados: {df.isnull().sum().sum()} nulos restantes")

# 4. Eliminar duplicados
df = df.drop_duplicates()
print(f"[4] Sin duplicados: {df.shape}")

# 5. Convertir tipos
df['Survived'] = df['Survived'].astype(bool)
df['Pclass']   = df['Pclass'].astype(str)

# 6. Renombrar
df = df.rename(columns={
    'Survived': 'sobrevivio', 'Pclass': 'clase',
    'Sex': 'sexo', 'Age': 'edad', 'SibSp': 'hermanos',
    'Parch': 'hijos', 'Fare': 'tarifa', 'Embarked': 'puerto'
})

print(f"\n✅ Dataset limpio:")
print(df.dtypes)
df.head()

### 🔹 Mini-ejercicio 3

Usando el Titanic limpiado del pipeline anterior:
1. ¿Cuántos pasajeros sobrevivieron? ¿Qué porcentaje representa?
2. Filtra solo los pasajeros de **primera clase** que **sobrevivieron**
3. ¿Cuál era la tarifa promedio por clase?
4. ¿Qué porcentaje de mujeres sobrevivió vs hombres?

In [ ]:
# Mini-ejercicio 3
import pandas as pd
df = pd.read_csv("data/titanic.csv")

# Aplica el pipeline de limpieza primero, luego responde:

---
## 🏁 Actividad Final — Semana 2

### Analiza el dataset Pokémon

Trabajando con `data/pokemon.csv`, responde las siguientes preguntas:

1. **Exploración inicial:**
   - ¿Cuántos pokémon hay en total?
   - ¿Cuántas columnas tiene el dataset?
   - ¿Hay valores nulos? ¿En qué columna?

2. **Filtrado:**
   - ¿Cuántos pokémon legendarios hay?
   - ¿Cuántos tipos distintos tiene `Type 1`?
   - Lista los pokémon con `Total` mayor a 600 ordenados de mayor a menor
   - ¿Cuál es el pokémon con mayor `Attack` por generación?

3. **Limpieza:**
   - La columna `Type 2` tiene valores nulos (pokémon monotipos). Rellénalos con `"Ninguno"`
   - Renombra `#` como `id` y `Legendary` como `legendario`
   - Elimina la columna `Total` (se puede calcular sumando las stats)

4. **Bonus:** Crea una nueva columna `velocidad_categoria` con:
   - `"Lento"` si Speed < 50
   - `"Normal"` si 50 ≤ Speed < 90
   - `"Rápido"` si Speed ≥ 90

In [ ]:
# Actividad Final
import pandas as pd
df = pd.read_csv("data/pokemon.csv")

# Tu código aquí:

In [ ]:
from IPython.core.display import HTML
HTML("""<style>
.output_png { display: table-cell; text-align: center; vertical-align: middle; }
table { border-collapse: collapse; }
</style>""")